# Render用のデプロイ設定ファイル

services:
  - type: web
    name: learning-log
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn learning_log.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: learning_log.settings
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: learning-log-db
          property: connectionString

databases:
  - name: learning-log-db
    plan: free
